In [18]:
import cv2
import os
import numpy as np
from matplotlib import pyplot as plt
from sklearn.cluster import KMeans


In [2]:
path='Clipped_NDVI/'
files=os.listdir(path)
data=[]
for i in range(len(files)):
    img=cv2.imread(path+files[i],0)
    data.append(img)

In [3]:
data=np.array(data)
print(data.shape)

(48, 2135, 2118)


In [7]:
np.histogram(data[0],bins=5)


(array([ 137827, 2263593, 1943007,  129908,   47595], dtype=int64),
 array([  0.,  51., 102., 153., 204., 255.]))

In [8]:
np.histogram(data[1],bins=5)


(array([ 241377, 2154059, 1929037,  149862,   47595], dtype=int64),
 array([  0.,  51., 102., 153., 204., 255.]))

In [9]:
np.histogram(data[5],bins=5)


(array([ 604171, 3756460,  113672,      32,   47595], dtype=int64),
 array([  0.,  51., 102., 153., 204., 255.]))

In [10]:
np.histogram(data[11],bins=5)


(array([2362916, 1979956,  129204,    2259,   47595], dtype=int64),
 array([  0.,  51., 102., 153., 204., 255.]))

In [11]:
a = np.histogram(data[11],bins=5)


In [12]:
a

(array([2362916, 1979956,  129204,    2259,   47595], dtype=int64),
 array([  0.,  51., 102., 153., 204., 255.]))

In [13]:
a[0]

array([2362916, 1979956,  129204,    2259,   47595], dtype=int64)

In [14]:
a[0][0]

2362916

In [15]:
var = []
for i in range(48):
    a = np.histogram(data[i],bins=5)
    var.append(a)

In [16]:
var


[(array([ 137827, 2263593, 1943007,  129908,   47595], dtype=int64),
  array([  0.,  51., 102., 153., 204., 255.])),
 (array([ 241377, 2154059, 1929037,  149862,   47595], dtype=int64),
  array([  0.,  51., 102., 153., 204., 255.])),
 (array([ 114125, 1996427, 2250029,  113754,   47595], dtype=int64),
  array([  0.,  51., 102., 153., 204., 255.])),
 (array([ 286833, 2698489, 1466851,   22162,   47595], dtype=int64),
  array([  0.,  51., 102., 153., 204., 255.])),
 (array([ 275473, 3425846,  771096,    1920,   47595], dtype=int64),
  array([  0.,  51., 102., 153., 204., 255.])),
 (array([ 604171, 3756460,  113672,      32,   47595], dtype=int64),
  array([  0.,  51., 102., 153., 204., 255.])),
 (array([ 645896, 3522597,  304923,     919,   47595], dtype=int64),
  array([  0.,  51., 102., 153., 204., 255.])),
 (array([ 460703, 3249132,  715956,   48544,   47595], dtype=int64),
  array([  0.,  51., 102., 153., 204., 255.])),
 (array([ 845771, 2884118,  674208,   70238,   47595], dtype=int

In [33]:
var1 = []
for i in range(48):
    var1.append((list(var[i][0])))
    

In [34]:
clusters = KMeans(n_clusters=2, random_state=0)

In [35]:
a = clusters.fit(var1)

In [36]:
var1

[[137827, 2263593, 1943007, 129908, 47595],
 [241377, 2154059, 1929037, 149862, 47595],
 [114125, 1996427, 2250029, 113754, 47595],
 [286833, 2698489, 1466851, 22162, 47595],
 [275473, 3425846, 771096, 1920, 47595],
 [604171, 3756460, 113672, 32, 47595],
 [645896, 3522597, 304923, 919, 47595],
 [460703, 3249132, 715956, 48544, 47595],
 [845771, 2884118, 674208, 70238, 47595],
 [1181457, 2768361, 511285, 13232, 47595],
 [1273332, 2858302, 330157, 12544, 47595],
 [2362916, 1979956, 129204, 2259, 47595],
 [2002314, 2325044, 146955, 22, 47595],
 [4224483, 233375, 16469, 8, 47595],
 [3011283, 1423016, 40036, 0, 47595],
 [860950, 2469151, 1058962, 85272, 47595],
 [130372, 1537834, 2700971, 105158, 47595],
 [161702, 1062335, 2754952, 495345, 47596],
 [100351, 1263573, 2867809, 242600, 47597],
 [116456, 1797721, 2413359, 146799, 47595],
 [176672, 2453569, 1781173, 62921, 47595],
 [136508, 2166292, 1976998, 194536, 47596],
 [60915, 2173592, 2133483, 106345, 47595],
 [78042, 846142, 2224487, 130

In [37]:
a

KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=300,
    n_clusters=2, n_init=10, n_jobs=1, precompute_distances='auto',
    random_state=0, tol=0.0001, verbose=0)

In [38]:
a.labels_

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 0])

In [40]:
clusters = KMeans(n_clusters=2, random_state=0,algorithm="elkan")

In [41]:
b = clusters.fit(var1)

In [42]:
b.labels_

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 0])

In [43]:
clusters = KMeans(n_clusters=2, random_state=0,tol=0.000001)

In [44]:
c = clusters.fit(var1)

In [45]:
b.labels_

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 0])